# Generated by Django 5.2 on 2025-04-20 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='author',
        ),
    ]
