# Generated by Django 5.2 on 2025-04-20 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_user_post_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='user',
            new_name='author',
        ),
    ]
