# Generated by Django 5.2 on 2025-04-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='content_markdown',
            field=models.TextField(blank=True, editable=False, max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
