# Generated by Django 5.2 on 2025-04-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_comments_content_markdown_post_is_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='content',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='comments',
            name='content_markdown',
            field=models.TextField(blank=True, editable=False, max_length=5000),
        ),
    ]
