# Generated by Django 5.2 on 2025-04-24 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_posttag_post_remove_posttag_tag_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Posts'},
        ),
    ]
