# Generated by Django 5.2 on 2025-04-25 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ['-index'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='categories',
            name='index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='categories',
            name='slug',
            field=models.SlugField(blank=True, default='no-slug', max_length=60),
        ),
    ]
