# Generated by Django 5.2 on 2025-04-25 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_categories_options_categories_index_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='id',
        ),
    ]
